"""empty message

Revision ID: 0278296a9b83
Revises: 81ffaf192e5a
Create Date: 2020-11-19 21:04:55.674970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0278296a9b83"
down_revision = "81ffaf192e5a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_discipline_name", table_name="discipline")
    op.drop_table("discipline")
    op.drop_table("exercisetodiscipline")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercisetodiscipline",
        sa.Column("exercise_id", sa.INTEGER(), nullable=False),
        sa.Column("discipline_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["discipline_id"],
            ["discipline.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercise.id"],
        ),
        sa.PrimaryKeyConstraint("exercise_id", "discipline_id"),
    )
    op.create_table(
        "discipline",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=128), nullable=True),
        sa.Column("description", sa.VARCHAR(length=512), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_discipline_name", "discipline", ["name"], unique=1)
    # ### end Alembic commands ###
